"""Unified Moss index builder for ANSIO — products / content / kols.

Builds the three ``ansio_``-prefixed indexes the ANSIO agent depends on, from
the deterministic data files in ``agent-py/`` (generated by ``gen_*.py``):

* ``ansio_products`` <- ``products.json``
* ``ansio_content``  <- ``content.jsonl`` + ``playbook.json`` (merged; the
  ``doc_type`` metadata field distinguishes the two — free-tier 3-index plan,
  per ``.omc/research/ansio-execution-v3/01-moss-apply.md`` route A1)
* ``ansio_kols``     <- ``kols.json`` (rebuilt under the ``ansio_`` prefix so it
  is isolated from the teammate's bare ``kols`` index)

Safety contract (NON-NEGOTIABLE):
* All index names carry the ``INDEX_PREFIX = "ansio_"`` constant. No bare
  string index names anywhere.
* Idempotency deletes ONLY ``ansio_``-prefixed indexes this script owns. It
  NEVER deletes or ``add_docs`` into any non-``ansio_`` index (``kols`` /
  ``memory`` / ``voice_ai-starter-*`` belong to a teammate).
* Before creating, it asserts there are enough free index slots. The Moss free
  Developer tier allows 3 indexes / project. If the project is already full of
  NON-ours indexes, it fails fast with route-B guidance instead of guessing.

Run (from agent-py/):
    ENV_FILE=.env uv run python src/build_indexes.py
    ENV_FILE=.env uv run python src/build_indexes.py --dry-run   # plan only, no writes

Needs MOSS_PROJECT_ID / MOSS_PROJECT_KEY (read from ENV_FILE, default .env.local).
"""

from __future__ import annotations

import asyncio
import json
import os
import sys
import time
from pathlib import Path

import certifi

# Ensure TLS works on macOS/uv venvs (mirrors build_kols_index.py / moss_contract.py).
os.environ.setdefault("SSL_CERT_FILE", certifi.where())

from dotenv import load_dotenv

load_dotenv(os.getenv("ENV_FILE", ".env.local"))

from moss import DocumentInfo, MossClient  # noqa: E402

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

INDEX_PREFIX = "ansio_"
IDX_PRODUCTS = INDEX_PREFIX + "products"
IDX_CONTENT = INDEX_PREFIX + "content"
IDX_KOLS = INDEX_PREFIX + "kols"

# Every index this script owns. Used for idempotent teardown and slot math.
OWNED_INDEXES = (IDX_PRODUCTS, IDX_CONTENT, IDX_KOLS)

# Moss free Developer tier: 3 indexes per project (docs.moss.dev/pricing).
FREE_TIER_INDEX_LIMIT = 3

AGENT_DIR = Path(__file__).resolve().parent.parent
PRODUCTS_PATH = AGENT_DIR / "products.json"
CONTENT_PATH = AGENT_DIR / "content.jsonl"
PLAYBOOK_PATH = AGENT_DIR / "playbook.json"
KOLS_PATH = AGENT_DIR / "kols.json"

DEFAULT_MODEL_ID = "moss-minilm"
MODEL_ID = os.getenv("MOSS_MODEL_ID", DEFAULT_MODEL_ID)

# doc_type tag applied to plain content rows so they are distinguishable from
# the playbook rows (qa / strategy / case) inside the merged ansio_content index.
CONTENT_DOC_TYPE = "content"


# ---------------------------------------------------------------------------
# Document loaders (all metadata coerced to str — Moss requires Dict[str,str])
# ---------------------------------------------------------------------------


def _coerce_metadata(raw: object) -> dict[str, str]:
    if not isinstance(raw, dict):
        return {}
    return {str(k): str(v) for k, v in raw.items()}


def _docs_from_entries(entries: list, *, extra_metadata: dict[str, str] | None = None) -> list[DocumentInfo]:
    docs: list[DocumentInfo] = []
    for entry in entries:
        if not isinstance(entry, dict):
            continue
        doc_id = entry.get("id")
        text = entry.get("text")
        if not doc_id or not text:
            continue
        metadata = _coerce_metadata(entry.get("metadata"))
        if extra_metadata:
            # Do not overwrite an explicit doc_type that the entry already set.
            for k, v in extra_metadata.items():
                metadata.setdefault(k, v)
        docs.append(DocumentInfo(id=str(doc_id), text=str(text), metadata=metadata))
    return docs


def _load_json_array(path: Path) -> list:
    if not path.exists():
        raise FileNotFoundError(f"Data file not found: {path}")
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise ValueError(f"{path.name} must be a JSON array")
    return data


def _load_jsonl(path: Path) -> list:
    if not path.exists():
        raise FileNotFoundError(f"Data file not found: {path}")
    rows = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        rows.append(json.loads(line))
    return rows


def load_products_docs() -> list[DocumentInfo]:
    return _docs_from_entries(_load_json_array(PRODUCTS_PATH))


def load_kols_docs() -> list[DocumentInfo]:
    return _docs_from_entries(_load_json_array(KOLS_PATH))


def load_content_docs() -> list[DocumentInfo]:
    """content.jsonl (tagged doc_type=content) + playbook.json (its own doc_type).

    Merging playbook into content is the free-tier 3-index plan: a single
    ``ansio_content`` index serves both, separable at query time with
    ``filter={"field": "doc_type", "condition": {"$eq": ...}}``.
    """
    content_rows = _load_jsonl(CONTENT_PATH)
    playbook_rows = _load_json_array(PLAYBOOK_PATH)
    content_docs = _docs_from_entries(
        content_rows, extra_metadata={"doc_type": CONTENT_DOC_TYPE}
    )
    playbook_docs = _docs_from_entries(playbook_rows)  # already carries doc_type
    merged = content_docs + playbook_docs

    seen: set[str] = set()
    for d in merged:
        if d.id in seen:
            raise ValueError(f"Duplicate doc id across content+playbook: {d.id}")
        seen.add(d.id)
    return merged


# ---------------------------------------------------------------------------
# Slot-safety + idempotency
# ---------------------------------------------------------------------------


def _index_names(index_infos: list) -> list[str]:
    names = []
    for i in index_infos:
        name = getattr(i, "index_name", None) or getattr(i, "name", None)
        if name:
            names.append(str(name))
    return names


async def _existing_names(client: MossClient) -> list[str]:
    return _index_names(await client.list_indexes())


def _assert_no_foreign_collision(existing: list[str]) -> None:
    """Defense in depth: refuse to run if a non-ours index ever carries our prefix."""
    foreign_ansio = [n for n in existing if n.startswith(INDEX_PREFIX) and n not in OWNED_INDEXES]
    if foreign_ansio:
        raise SystemExit(
            "ABORT: found ansio_-prefixed indexes this script does not own: "
            f"{foreign_ansio}. Refusing to touch them."
        )


def _check_slot_budget(existing: list[str]) -> tuple[list[str], list[str], int]:
    """Return (ours_present, foreign, free_slots_after_teardown)."""
    ours = [n for n in existing if n in OWNED_INDEXES]
    foreign = [n for n in existing if n not in OWNED_INDEXES]
    # After we delete our own indexes (idempotent rebuild), occupancy == len(foreign).
    free_after_teardown = FREE_TIER_INDEX_LIMIT - len(foreign)
    return ours, foreign, free_after_teardown


# ---------------------------------------------------------------------------
# Build
# ---------------------------------------------------------------------------


async def _build_one(client: MossClient, name: str, docs: list[DocumentInfo]) -> dict:
    t0 = time.perf_counter()
    res = await client.create_index(name, docs, MODEL_ID)
    elapsed = time.perf_counter() - t0
    info = {
        "index": getattr(res, "index_name", name),
        "docs": getattr(res, "doc_count", len(docs)),
        "job": getattr(res, "job_id", None),
        "input_docs": len(docs),
        "build_s": round(elapsed, 2),
    }
    print(
        f"  [DONE] {name}: {info['docs']} docs in {info['build_s']}s "
        f"(input={info['input_docs']}, job={info['job']})"
    )
    return info


async def build_all(*, dry_run: bool = False, lean: bool = False) -> int:
    pid, key = os.getenv("MOSS_PROJECT_ID"), os.getenv("MOSS_PROJECT_KEY")
    if not pid or not key:
        raise SystemExit(
            "Missing MOSS_PROJECT_ID / MOSS_PROJECT_KEY "
            "(set them in your ENV_FILE, default .env.local)."
        )

    # Load all docs first so a data error fails before any network mutation.
    products = load_products_docs()
    content = load_content_docs()
    kols = load_kols_docs()
    if lean:
        # LEAN mode: real creators + real content only (drops the 1000 synthetic
        # KOLs + synthetic content). Built to fit the Moss free-tier monthly
        # ingest cap (50MB) and to keep the index high-signal: every retrieved
        # creator is a real person. Playbook (pb-*) is kept for objection handling.
        kols = [d for d in kols if (getattr(d, "metadata", {}) or {}).get("source") == "real"]
        content = [
            d for d in content
            if d.id.startswith(("content-real", "content-cur", "pb-"))
        ]
    # Smallest-first ordering so an ingest-cap hit restores the most indexes
    # before failing (products < kols < content under lean).
    plan = {
        IDX_PRODUCTS: products,
        IDX_KOLS: kols,
        IDX_CONTENT: content,
    }
    print("Build plan (model=%s)%s:" % (MODEL_ID, " [LEAN: real-only]" if lean else ""))
    for name, docs in plan.items():
        print(f"  - {name}: {len(docs)} docs")

    client = MossClient(pid, key)
    existing = await _existing_names(client)
    print(f"\nExisting indexes in project ({len(existing)}/{FREE_TIER_INDEX_LIMIT}): {existing}")

    _assert_no_foreign_collision(existing)
    ours, foreign, free_after = _check_slot_budget(existing)
    need = len(plan)
    print(f"  ours (will rebuild): {ours}")
    print(f"  foreign (untouched): {foreign}")
    print(f"  free slots after teardown of ours: {free_after}  | need: {need}")

    if free_after < need:
        print(
            "\nBLOCKED: not enough free index slots.\n"
            f"  Free-tier limit is {FREE_TIER_INDEX_LIMIT} indexes/project; "
            f"{len(foreign)} are occupied by NON-ours indexes ({foreign}).\n"
            "  This script will NOT delete foreign indexes. Per B3 report, switch to\n"
            "  ROUTE B: self-register a dedicated Moss project (portal.usemoss.dev),\n"
            "  put its MOSS_PROJECT_ID / MOSS_PROJECT_KEY in .env, and re-run.\n"
        )
        return 2

    if dry_run:
        print("\n--dry-run: no indexes created or deleted.")
        return 0

    # Idempotent teardown: delete ONLY our own indexes that already exist.
    for name in OWNED_INDEXES:
        if name in existing:
            print(f"\n[idempotent] deleting existing owned index '{name}'...")
            ok = await client.delete_index(name)
            print(f"  deleted={ok}")

    print("\nBuilding indexes...")
    results = []
    failures = []
    for name, docs in plan.items():
        try:
            results.append(await _build_one(client, name, docs))
        except Exception as e:
            # Resilient: one index failing (e.g. ingest-cap 429) must not abort
            # the rest — restore as many indexes as the quota allows.
            print(f"  [FAIL] {name}: {type(e).__name__}: {str(e)[:200]}")
            failures.append(name)

    print("\nansio_ indexes built:")
    for r in results:
        print(f"  {r['index']}: {r['docs']} docs ({r['build_s']}s)")
    if failures:
        print(f"\nFAILED ({len(failures)}): {failures}")
        print(
            "  If the cause is HTTP 429 USAGE_LIMIT_EXCEEDED (monthly 50MB ingest\n"
            "  cap), options: (1) wait for the monthly reset, (2) use a fresh Moss\n"
            "  project (new MOSS_PROJECT_ID/KEY in .env), or (3) re-run with --lean\n"
            "  for a smaller real-only payload."
        )
        return 3
    return 0


def main() -> None:
    dry_run = "--dry-run" in sys.argv
    lean = "--lean" in sys.argv
    rc = asyncio.run(build_all(dry_run=dry_run, lean=lean))
    sys.exit(rc)


if __name__ == "__main__":
    main()
